// JavaScript Document
document.write('<script type="text/javascript" src="/common/js/jquery.js"></script>');
document.write('<script type="text/javascript" src="/common/js/smooth.pack.js"></script>');
document.write('<script type="text/javascript" src="/common/js/jquery.corner.js"></script>'); 
document.write('<script type="text/javascript" src="/common/js/jquery.mousewheel.js"></script>'); 
document.write('<script type="text/javascript" src="/common/js/jquery.jscrollpane.min.js"></script>'); 
document.write('<script type="text/javascript" src="/common/js/jquery.nivo.slider.pack.js"></script>'); 
document.write('<script type="text/javascript" src="/common/js/common.js"></script>');
document.write('<script type="text/javascript" src="/common/js/inquiry.js"></script>');
document.write('<script type="text/javascript" src="/common/js/jquery.func.js"></script>');